# import section
from datetime import datetime

# end import section

# Functions Section
"""to convert date to a string"""


def str_dates(x):
    y = []
    for j in x:
        y.append(str(j))
    return y


"""create liste with a range"""


def create_list(x, y):
    liste = [i for i in range(x, y)]
    return liste


"""create a ea card"""
def ea_card(name, id, dob):
    return [
        {'name': name,
         'id': id,
         'dob': dob
         }
    ]
# end Functions Section

# For Dates

# Date now
now = datetime.now()

# Month's Days
days = str_dates(create_list(1, 32)).insert(0, 'Jour')
# Months of the year
months = str_dates(create_list(1, 13)).insert(0, 'Mois')
# Years from 1915 to now
years = str_dates(create_list(1915, now.year + 1)).append('Année')
# Days of the week
week_days = ['Lun',
             'Mar',
             'Mer',
             'Jeu',
             'Ven',
             'Sam',
             'Dim',
             ]
# US States
us_states = [
    ('Alabama', 'AL'),
    ('Alaska', 'AK'),
    ('American Samoa', 'AS'),
    ('Arizona', 'AZ'),
    ('Arkansas', 'AR'),
    ('California', 'CA'),
    ('Colorado', 'CO'),
    ('Connecticut', 'CT'),
    ('Delaware', 'DE'),
    ('District of Columbia', 'DC'),
    ('Federated States of Micronesia', 'FM'),
    ('Florida', 'FL'),
    ('Georgia', 'GA'),
    ('Guam', 'GU'),
    ('Hawaii', 'HI'),
    ('Idaho', 'ID'),
    ('Illinois', 'IL'),
    ('Indiana', 'IN'),
    ('Iowa', 'IA'),
    ('Kansas', 'KS'),
    ('Kentucky', 'KY'),
    ('Louisiana', 'LA'),
    ('Maine', 'ME'),
    ('Marshall Islands', 'MH'),
    ('Maryland', 'MD'),
    ('Massachusetts', 'MA'),
    ('Michigan', 'MI'),
    ('Minnesota', 'MN'),
    ('Mississippi', 'MS'),
    ('Missouri', 'MO'),
    ('Montana', 'MT'),
    ('Nebraska', 'NE'),
    ('Nevada', 'NV'),
    ('New Hampshire', 'NH'),
    ('New Jersey', 'NJ'),
    ('New Mexico', 'NM'),
    ('New York', 'NY'),
    ('North Carolina', 'NC'),
    ('North Dakota', 'ND'),
    ('Northern Mariana Islands', 'MP'),
    ('Ohio', 'OH'),
    ('Oklahoma', 'OK'),
    ('Oregon', 'OR'),
    ('Palau', 'PW'),
    ('Pennsylvania', 'PA'),
    ('Puerto Rico', 'PR'),
    ('Rhode Island', 'RI'),
    ('South Carolina', 'SC'),
    ('South Dakota', 'SD'),
    ('Tennessee', 'TN'),
    ('Texas', 'TX'),
    ('Utah', 'UT'),
    ('Vermont', 'VT'),
    ('Virgin Islands', 'VI'),
    ('Virginia', 'VA'),
    ('Washington', 'WA'),
    ('West Virginia', 'WV'),
    ('Wisconsin', 'WI'),
    ('Wyoming', 'WY'),
    ('Armed Forces Africa', 'AE'),
    ('Armed Forces Americas (except Canada)', 'AA'),
    ('Armed Forces Canada', 'AE'),
    ('Armed Forces Europe', 'AE'),
    ('Armed Forces Middle East', 'AE'),
    ('Armed Forces Pacific', 'AP'),
]
# CA States
ca_states = [
    ('Alberta', 'Alberta', 'AB'),
    ('British Columbia', 'Colombie-Britannique', 'BC'),
    ('Manitoba', 'Manitoba', 'MB'),
    ('New Brunswick', 'Nouveau-Brunswic', 'NB'),
    ('Newfoundland', 'Terre-Neuve', 'NF'),
    ('Northwest Territories', 'Territoires du Nord-Ouest', 'NT'),
    ('Nova Scotia', 'Nouvelle-Écosse', 'NS'),
    ('Nunavut', 'Nunavut', 'NU'),
    ('Ontario', 'Ontario', 'ON'),
    ('Prince Edward Island', 'Île-du-Prince-Édouard', 'PE'),
    ('Quebec', 'Québec', 'QC'),
    ('Saskatchewan', 'Saskatchewan', 'SK'),
    ('Yukon', 'Yukon', 'YT'),
]
# World's Countries
countries = [
           ('US', 'United States'),
           ('AF', 'Afghanistan'),
           ('AL', 'Albania'),
           ('DZ', 'Algeria'),
           ('AS', 'American Samoa'),
           ('AD', 'Andorra'),
           ('AO', 'Angola'),
           ('AI', 'Anguilla'),
           ('AQ', 'Antarctica'),
           ('AG', 'Antigua And Barbuda'),
           ('AR', 'Argentina'),
           ('AM', 'Armenia'),
           ('AW', 'Aruba'),
           ('AU', 'Australia'),
           ('AT', 'Austria'),
           ('AZ', 'Azerbaijan'),
           ('BS', 'Bahamas'),
           ('BH', 'Bahrain'),
           ('BD', 'Bangladesh'),
           ('BB', 'Barbados'),
           ('BY', 'Belarus'),
           ('BE', 'Belgium'),
           ('BZ', 'Belize'),
           ('BJ', 'Benin'),
           ('BM', 'Bermuda'),
           ('BT', 'Bhutan'),
           ('BO', 'Bolivia'),
           ('BA', 'Bosnia And Herzegowina'),
           ('BW', 'Botswana'),
           ('BV', 'Bouvet Island'),
           ('BR', 'Brazil'),
           ('BN', 'Brunei Darussalam'),
           ('BG', 'Bulgaria'),
           ('BF', 'Burkina Faso'),
           ('BI', 'Burundi'),
           ('KH', 'Cambodia'),
           ('CM', 'Cameroon'),
           ('CA', 'Canada'),
           ('CV', 'Cape Verde'),
           ('KY', 'Cayman Islands'),
           ('CF', 'Central African Rep'),
           ('TD', 'Chad'),
           ('CL', 'Chile'),
           ('CN', 'China'),
           ('CX', 'Christmas Island'),
           ('CC', 'Cocos Islands'),
           ('CO', 'Colombia'),
           ('KM', 'Comoros'),
           ('CG', 'Congo'),
           ('CK', 'Cook Islands'),
           ('CR', 'Costa Rica'),
           ('CI', 'Cote D`ivoire'),
           ('HR', 'Croatia'),
           ('CU', 'Cuba'),
           ('CY', 'Cyprus'),
           ('CZ', 'Czech Republic'),
           ('DK', 'Denmark'),
           ('DJ', 'Djibouti'),
           ('DM', 'Dominica'),
           ('DO', 'Dominican Republic'),
           ('TP', 'East Timor'),
           ('EC', 'Ecuador'),
           ('EG', 'Egypt'),
           ('SV', 'El Salvador'),
           ('GQ', 'Equatorial Guinea'),
           ('ER', 'Eritrea'),
           ('EE', 'Estonia'),
           ('ET', 'Ethiopia'),
           ('FK', 'Falkland Islands (Malvinas)'),
           ('FO', 'Faroe Islands'),
           ('FJ', 'Fiji'),
           ('FI', 'Finland'),
           ('FR', 'France'),
           ('GF', 'French Guiana'),
           ('PF', 'French Polynesia'),
           ('TF', 'French S. Territories'),
           ('GA', 'Gabon'),
           ('GM', 'Gambia'),
           ('GE', 'Georgia'),
           ('DE', 'Germany'),
           ('GH', 'Ghana'),
           ('GI', 'Gibraltar'),
           ('GR', 'Greece'),
           ('GL', 'Greenland'),
           ('GD', 'Grenada'),
           ('GP', 'Guadeloupe'),
           ('GU', 'Guam'),
           ('GT', 'Guatemala'),
           ('GN', 'Guinea'),
           ('GW', 'Guinea-bissau'),
           ('GY', 'Guyana'),
           ('HT', 'Haiti'),
           ('HN', 'Honduras'),
           ('HK', 'Hong Kong'),
           ('HU', 'Hungary'),
           ('IS', 'Iceland'),
           ('IN', 'India'),
           ('ID', 'Indonesia'),
           ('IR', 'Iran'),
           ('IQ', 'Iraq'),
           ('IE', 'Ireland'),
           ('IL', 'Israel'),
           ('IT', 'Italy'),
           ('JM', 'Jamaica'),
           ('JP', 'Japan'),
           ('JO', 'Jordan'),
           ('KZ', 'Kazakhstan'),
           ('KE', 'Kenya'),
           ('KI', 'Kiribati'),
           ('KP', 'Korea (North)'),
           ('KR', 'Korea (South)'),
           ('KW', 'Kuwait'),
           ('KG', 'Kyrgyzstan'),
           ('LA', 'Laos'),
           ('LV', 'Latvia'),
           ('LB', 'Lebanon'),
           ('LS', 'Lesotho'),
           ('LR', 'Liberia'),
           ('LY', 'Libya'),
           ('LI', 'Liechtenstein'),
           ('LT', 'Lithuania'),
           ('LU', 'Luxembourg'),
           ('MO', 'Macau'),
           ('MK', 'Macedonia'),
           ('MG', 'Madagascar'),
           ('MW', 'Malawi'),
           ('MY', 'Malaysia'),
           ('MV', 'Maldives'),
           ('ML', 'Mali'),
           ('MT', 'Malta'),
           ('MH', 'Marshall Islands'),
           ('MQ', 'Martinique'),
           ('MR', 'Mauritania'),
           ('MU', 'Mauritius'),
           ('YT', 'Mayotte'),
           ('MX', 'Mexico'),
           ('FM', 'Micronesia'),
           ('MD', 'Moldova'),
           ('MC', 'Monaco'),
           ('MN', 'Mongolia'),
           ('MS', 'Montserrat'),
           ('MA', 'Morocco'),
           ('MZ', 'Mozambique'),
           ('MM', 'Myanmar'),
           ('NA', 'Namibia'),
           ('NR', 'Nauru'),
           ('NP', 'Nepal'),
           ('NL', 'Netherlands'),
           ('AN', 'Netherlands Antilles'),
           ('NC', 'New Caledonia'),
           ('NZ', 'New Zealand'),
           ('NI', 'Nicaragua'),
           ('NE', 'Niger'),
           ('NG', 'Nigeria'),
           ('NU', 'Niue'),
           ('NF', 'Norfolk Island'),
           ('MP', 'Northern Mariana Islands'),
           ('NO', 'Norway'),
           ('OM', 'Oman'),
           ('PK', 'Pakistan'),
           ('PW', 'Palau'),
           ('PA', 'Panama'),
           ('PG', 'Papua New Guinea'),
           ('PY', 'Paraguay'),
           ('PE', 'Peru'),
           ('PH', 'Philippines'),
           ('PN', 'Pitcairn'),
           ('PL', 'Poland'),
           ('PT', 'Portugal'),
           ('PR', 'Puerto Rico'),
           ('QA', 'Qatar'),
           ('RE', 'Reunion'),
           ('RO', 'Romania'),
           ('RU', 'Russian Federation'),
           ('RW', 'Rwanda'),
           ('KN', 'Saint Kitts And Nevis'),
           ('LC', 'Saint Lucia'),
           ('VC', 'St Vincent/Grenadines'),
           ('WS', 'Samoa'),
           ('SM', 'San Marino'),
           ('ST', 'Sao Tome'),
           ('SA', 'Saudi Arabia'),
           ('SN', 'Senegal'),
           ('SC', 'Seychelles'),
           ('SL', 'Sierra Leone'),
           ('SG', 'Singapore'),
           ('SK', 'Slovakia'),
           ('SI', 'Slovenia'),
           ('SB', 'Solomon Islands'),
           ('SO', 'Somalia'),
           ('ZA', 'South Africa'),
           ('ES', 'Spain'),
           ('LK', 'Sri Lanka'),
           ('SH', 'St. Helena'),
           ('PM', 'St.Pierre'),
           ('SD', 'Sudan'),
           ('SR', 'Suriname'),
           ('SZ', 'Swaziland'),
           ('SE', 'Sweden'),
           ('CH', 'Switzerland'),
           ('SY', 'Syrian Arab Republic'),
           ('TW', 'Taiwan'),
           ('TJ', 'Tajikistan'),
           ('TZ', 'Tanzania'),
           ('TH', 'Thailand'),
           ('TG', 'Togo'),
           ('TK', 'Tokelau'),
           ('TO', 'Tonga'),
           ('TT', 'Trinidad And Tobago'),
           ('TN', 'Tunisia'),
           ('TR', 'Turkey'),
           ('TM', 'Turkmenistan'),
           ('TV', 'Tuvalu'),
           ('UG', 'Uganda'),
           ('UA', 'Ukraine'),
           ('AE', 'United Arab Emirates'),
           ('UK', 'United Kingdom'),
           ('UY', 'Uruguay'),
           ('UZ', 'Uzbekistan'),
           ('VU', 'Vanuatu'),
           ('VA', 'Vatican City State'),
           ('VE', 'Venezuela'),
           ('VN', 'Viet Nam'),
           ('VG', 'Virgin Islands (British)'),
           ('VI', 'Virgin Islands (U.S.)'),
           ('EH', 'Western Sahara'),
           ('YE', 'Yemen'),
           ('YU', 'Yugoslavia'),
           ('ZR', 'Zaire'),
           ('ZM', 'Zambia'),
           ('ZW', 'Zimbabwe')
]

